# External validation: Molly, driving the REAL nequip-allegro model through `ASECalculator`
# (PythonCall), reproduces the package's own energy/forces from
# data/allegro_reference/allegro_package_ref.json (generated by test/allegro_package_reference.py).
#
# This is the "call the existing package from Python" check from Joe's #283 review: the reference is
# the package's output, and Molly reproduces it via the package's ASE calculator — no re-implementation
# in the loop. It needs PythonCall plus a Python env with nequip-allegro, so CI (which has neither
# PythonCall in the test deps nor the package) skips it; run it offline with:
#
#   JULIA_CONDAPKG_BACKEND=Null JULIA_PYTHONCALL_EXE=<env>/bin/python \
#   PYTHONPATH=$(dirname this_file) julia --project=<env-with-Molly+PythonCall+JSON3> \
#       test/allegro_ase_validation.jl

using Test, Molly, JSON3
using Molly: SVector

const ASE_REF = joinpath(@__DIR__, "..", "data", "allegro_reference", "allegro_package_ref.json")
const HAVE_PYTHONCALL = Base.identify_package("PythonCall") !== nothing

@testset "allegro_ase_validation" begin
    if !HAVE_PYTHONCALL || !isfile(ASE_REF)
        @info "Skipping external ASE validation (needs PythonCall + a Python env with " *
              "nequip-allegro and $(basename(ASE_REF))); not run in CI"
        @test true
    else
        @eval import PythonCall
        ref = JSON3.read(read(ASE_REF, String))
        tn = String.(ref.type_names)

        PythonCall.pyimport("sys").path.insert(0, @__DIR__)   # so test/allegro_ase_calc.py imports
        ase_calc = PythonCall.pyimport("allegro_ase_calc").make_calc()

        for sysj in ref.systems
            coords = [SVector{3,Float64}(Float64.(c)...) for c in sysj.coords_A]   # Angstrom
            elems = [tn[Int(t) + 1] for t in sysj.types]
            n = length(elems)
            atoms = [Atom(mass=1.0) for _ in 1:n]
            boundary = CubicBoundary(50.0)
            calc = ASECalculator(ase_calc=ase_calc, atoms=atoms, coords=coords, boundary=boundary, elements=elems)
            sys = System(atoms=atoms, coords=coords, boundary=boundary, general_inters=(calc,),
                         energy_units=NoUnits, force_units=NoUnits)
            E = potential_energy(sys); F = forces(sys)
            Fref = [SVector{3,Float64}(fr...) for fr in sysj.forces]
            @test isapprox(Float64(E), Float64(sysj.energy); atol=1e-6)
            @test maximum(maximum(abs.(F[i] .- Fref[i])) for i in 1:n) < 1e-6
        end
    end
end
