# Tests for the O(3)-equivariant primitives in src/equivariant/ (the foundation of the native
# Allegro potential). These run with a bare `using Molly` — no Lux/HDF5/GPU or trained model
# needed — and validate:
#   * real spherical-harmonic normalization and equivariance,
#   * analytic gradients of every primitive against finite differences,
#   * exact equivariance / invariance of the Clebsch-Gordan tensor product,
#   * the tensor-product and equivariant-linear VJPs against finite differences.
#
# Matching e3nn's exact conventions bit-for-bit (a prerequisite for loading trained weights) is
# checked by a separate, reference-gated test generated by test/allegro_reference.py.

using Molly
using StaticArrays
using LinearAlgebra
using Test

# Deterministic proper rotation (QR of a fixed pseudo-random matrix; no RNG-seed coupling).
function _rand_rotation(seed)
    A = zeros(3, 3)
    for i in 1:3, j in 1:3
        A[i, j] = mod(sin(seed * 12.9898 + i * 3.17 + j * 7.13) * 43758.5453, 1.0) - 0.5
    end
    R = Matrix(qr(A).Q)
    det(R) < 0 && (R[:, 1] .*= -1)
    return SMatrix{3,3,Float64}(R)
end

_rand_vec(seed) = SVector{3,Float64}(sin(seed * 1.1) + 0.3, cos(seed * 2.3) - 0.2, sin(seed * 0.7) * 0.9 + 0.4)

@testset "Equivariant primitives" begin
    @testset "Real SH component normalization (Σ_m Y²= 2l+1)" begin
        for s in 1:20
            Y = Molly.real_sph_harm(2, _rand_vec(s))
            @test isapprox(Y[1]^2, 1.0; atol=1e-10)
            @test isapprox(sum(Y[i]^2 for i in 2:4), 3.0; atol=1e-9)
            @test isapprox(sum(Y[i]^2 for i in 5:9), 5.0; atol=1e-9)
        end
    end

    @testset "Real SH l=1 equivariance (D¹ = R)" begin
        for s in 1:10
            R = _rand_rotation(s); r = _rand_vec(s + 100)
            Y = Molly.real_sph_harm(1, r); Yr = Molly.real_sph_harm(1, R * r)
            @test isapprox(SVector{3}(Yr[2], Yr[3], Yr[4]), R * SVector{3}(Y[2], Y[3], Y[4]); atol=1e-9)
        end
    end

    @testset "Real SH gradient vs finite differences" begin
        for s in 1:10
            r = _rand_vec(s + 7)
            Y, J = Molly.real_sph_harm_grad(2, r)
            @test isapprox(Y, Molly.real_sph_harm(2, r); atol=1e-10)
            h = 1e-6
            for b in 1:3
                fd = (Molly.real_sph_harm(2, setindex(r, r[b] + h, b)) .-
                      Molly.real_sph_harm(2, setindex(r, r[b] - h, b))) ./ (2h)
                for i in 1:9
                    @test isapprox(J[i, b], fd[i]; atol=1e-5, rtol=1e-4)
                end
            end
        end
    end

    @testset "Bessel + envelope gradients vs finite differences" begin
        rc = 5.0
        for s in 1:10
            r = clamp(0.3 + 4.0 * abs(_rand_vec(s)[1] / 2), 0.2, 4.8)
            _, dB = Molly.bessel_basis_grad(r, rc, Val(8))
            _, du = Molly.poly_envelope_grad(r, rc, 6)
            _, dR = Molly.radial_embedding(r, rc, Val(8), 6)
            h = 1e-6
            Bp, _ = Molly.bessel_basis_grad(r + h, rc, Val(8)); Bm, _ = Molly.bessel_basis_grad(r - h, rc, Val(8))
            @test isapprox(dB, (Bp .- Bm) ./ (2h); atol=1e-3, rtol=1e-4)
            @test isapprox(du, (Molly.poly_envelope(r + h, rc, 6) - Molly.poly_envelope(r - h, rc, 6)) / (2h);
                           atol=1e-6, rtol=1e-5)
            Rp, _ = Molly.radial_embedding(r + h, rc, Val(8), 6); Rm, _ = Molly.radial_embedding(r - h, rc, Val(8), 6)
            @test isapprox(dR, (Rp .- Rm) ./ (2h); atol=1e-3, rtol=1e-4)
        end
    end

    @testset "Tensor product 1o⊗1o→0e is rotation-invariant" begin
        paths = Molly.TensorProductPaths(Molly.Irreps("1x1o"), Molly.Irreps("1x1o"), Molly.Irreps("1x0e"))
        cg = Molly.build_sparse_cg(paths; T=Float64); w = [1.0]
        for s in 1:10
            R = _rand_rotation(s); a = _rand_vec(s + 3); b = _rand_vec(s + 9)
            x = collect(Molly.real_sph_harm(1, a)[2:4]); y = collect(Molly.real_sph_harm(1, b)[2:4])
            z = Molly.tensor_product(paths, cg, x, y, w)
            xr = collect(Molly.real_sph_harm(1, R * a)[2:4]); yr = collect(Molly.real_sph_harm(1, R * b)[2:4])
            zr = Molly.tensor_product(paths, cg, xr, yr, w)
            @test isapprox(z[1], zr[1]; atol=1e-8)
        end
    end

    @testset "Tensor product 1o⊗1o→1e output is equivariant" begin
        paths = Molly.TensorProductPaths(Molly.Irreps("1x1o"), Molly.Irreps("1x1o"), Molly.Irreps("1x1e"))
        cg = Molly.build_sparse_cg(paths; T=Float64); w = [1.0]
        for s in 1:10
            R = _rand_rotation(s); a = _rand_vec(s + 3); b = _rand_vec(s + 9)
            x = collect(Molly.real_sph_harm(1, a)[2:4]); y = collect(Molly.real_sph_harm(1, b)[2:4])
            z = Molly.tensor_product(paths, cg, x, y, w)
            xr = collect(Molly.real_sph_harm(1, R * a)[2:4]); yr = collect(Molly.real_sph_harm(1, R * b)[2:4])
            zr = Molly.tensor_product(paths, cg, xr, yr, w)
            @test isapprox(SVector{3}(zr...), R * SVector{3}(z...); atol=1e-8)
        end
    end

    @testset "Tensor product 2e⊗2e→0e invariance (l=2 end-to-end)" begin
        paths = Molly.TensorProductPaths(Molly.Irreps("1x2e"), Molly.Irreps("1x2e"), Molly.Irreps("1x0e"))
        cg = Molly.build_sparse_cg(paths; T=Float64); w = [1.0]
        for s in 1:10
            R = _rand_rotation(s); a = _rand_vec(s + 3); b = _rand_vec(s + 9)
            x = collect(Molly.real_sph_harm(2, a)[5:9]); y = collect(Molly.real_sph_harm(2, b)[5:9])
            z = Molly.tensor_product(paths, cg, x, y, w)
            xr = collect(Molly.real_sph_harm(2, R * a)[5:9]); yr = collect(Molly.real_sph_harm(2, R * b)[5:9])
            zr = Molly.tensor_product(paths, cg, xr, yr, w)
            @test isapprox(z[1], zr[1]; atol=1e-8)
        end
    end

    @testset "Tensor-product VJP vs finite differences" begin
        paths = Molly.TensorProductPaths(Molly.Irreps("2x1o"), Molly.Irreps("1x1o"),
                                         Molly.Irreps("2x0e+2x1e+2x2e"))
        cg = Molly.build_sparse_cg(paths; T=Float64)
        x = [sin(0.7i) + 0.1 for i in 1:paths.in1.dim]
        y = [cos(0.3i) - 0.2 for i in 1:paths.in2.dim]
        w = [0.5 + 0.2sin(1.3i) for i in 1:paths.n_weights]
        ḡ = [cos(0.9i) + 0.3 for i in 1:paths.out.dim]
        x̄, ȳ, w̄ = Molly.tensor_product_vjp(paths, cg, x, y, w, ḡ)
        h = 1e-6
        E(xx, yy, ww) = sum(Molly.tensor_product(paths, cg, xx, yy, ww) .* ḡ)
        for i in 1:paths.in1.dim
            xp = copy(x); xp[i] += h; xm = copy(x); xm[i] -= h
            @test isapprox(x̄[i], (E(xp, y, w) - E(xm, y, w)) / (2h); atol=1e-6, rtol=1e-5)
        end
        for i in 1:paths.in2.dim
            yp = copy(y); yp[i] += h; ym = copy(y); ym[i] -= h
            @test isapprox(ȳ[i], (E(x, yp, w) - E(x, ym, w)) / (2h); atol=1e-6, rtol=1e-5)
        end
        for i in 1:paths.n_weights
            wp = copy(w); wp[i] += h; wm = copy(w); wm[i] -= h
            @test isapprox(w̄[i], (E(x, y, wp) - E(x, y, wm)) / (2h); atol=1e-6, rtol=1e-5)
        end
    end

    @testset "e3nn convention pin (real SH values)" begin
        # Exact values from e3nn 0.6.0 o3.spherical_harmonics([0,1,2], x, normalize=true,
        # normalization="component"). Pins the axis order / normalization / l=2 basis so trained
        # e3nn/Allegro weights transfer. Regenerate with test/allegro_reference.py.
        cases = [
            (SVector(0.3, -0.5, 0.8),
             [1.0, 0.524890659168, -0.87481776528, 1.399708424448, 0.948485717439,
              -0.592803573399, -0.262395732054, -1.580809529064, 1.086806551232]),
            (SVector(0.1, 0.2, -0.4),
             [1.0, 0.377964473009, 0.755928946018, -1.511857892037, -0.737711113563,
              0.368855556782, -0.47915742375, -1.475422227127, 1.383208337931]),
        ]
        for (v, ref) in cases
            @test isapprox(collect(Molly.real_sph_harm(2, v)), ref; atol=1e-9)
        end
    end

    @testset "e3nn convention pin (Wigner-3j coupling)" begin
        # e3nn o3.wigner_3j(1,1,2) nonzeros; build_sparse_cg(:wigner3j) must match bit-for-bit.
        w3j = Dict((1, 1, 3) => -0.182574, (1, 1, 5) => -0.316228, (1, 2, 2) => 0.316228,
                   (1, 3, 1) => 0.316228, (2, 1, 2) => 0.316228, (2, 2, 3) => 0.365148,
                   (2, 3, 4) => 0.316228, (3, 1, 1) => 0.316228, (3, 2, 4) => 0.316228,
                   (3, 3, 3) => -0.182574, (3, 3, 5) => 0.316228)  # 1-based (i,j,k)
        dense = Molly._real_cg_dense(1, 1, 2) ./ sqrt(5.0)  # CG → wigner_3j normalization
        for i in 1:3, j in 1:3, k in 1:5
            ref = get(w3j, (i, j, k), 0.0)
            @test isapprox(dense[i, j, k], ref; atol=1e-5)
        end
    end

    @testset "Equivariant-linear VJP vs finite differences" begin
        irs = Molly.Irreps("2x0e+2x1e")
        W = [reshape([0.3, 0.1, -0.2, 0.5], 2, 2), reshape([0.4, -0.1, 0.2, 0.6], 2, 2)]
        b = [[0.05, -0.03], [0.0, 0.0]]
        lin = Molly.EquivariantLinear(irs, irs, W, b)
        x = [sin(0.5i) + 0.2 for i in 1:irs.dim]
        ḡ = [cos(0.6i) - 0.1 for i in 1:irs.dim]
        x̄, W̄, b̄ = Molly.eqlinear_vjp(lin, x, ḡ)
        h = 1e-6
        E(xx) = sum(Molly.eqlinear_forward(lin, xx) .* ḡ)
        for i in 1:irs.dim
            xp = copy(x); xp[i] += h; xm = copy(x); xm[i] -= h
            @test isapprox(x̄[i], (E(xp) - E(xm)) / (2h); atol=1e-6, rtol=1e-5)
        end
    end
end
