# ML potential tests
# Run after generating reference data:
#   python scripts/torchani_reference.py --skip-protein
# Then:
#   julia --project -e 'using Molly, Lux, HDF5; include("test/ml_potentials.jl")'

using Molly
using Lux, HDF5
using StaticArrays, Unitful, LinearAlgebra
using Test, JSON3, Random

# Path to reference data generated by scripts/torchani_reference.py
const REF_DIR = joinpath(@__DIR__, "..", "data", "ani_reference")

# ============================================================================
# Test 1: AEV validation against TorchANI for N₂ dimer
# ============================================================================

@testset "ANI AEV: N₂ dimer matches TorchANI reference" begin
    ref_path = joinpath(REF_DIR, "n2_aevs.json")
    if !isfile(ref_path)
        @warn "Reference AEV file not found at $ref_path — run scripts/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        aev_ref = Float32.(reduce(hcat, ref.aevs)')   # (2, 1008) reference

        # Build the same N₂ dimer system
        # TorchANI ANI-2x default AEV parameters (from torchani source)
        # These must match what torchani_reference.py exports in ani2x.h5
        h5_path = joinpath(REF_DIR, "ani2x.h5")
        if !isfile(h5_path)
            @warn "ani2x.h5 not found at $h5_path — run scripts/torchani_reference.py first"
            @test_broken false
        else
            pot = ANIPotential(h5_path)
            n_species = length(pot.species_map)

            # N₂ dimer: 2 N atoms, bond length 1.1 Å, no PBC (infinite box)
            coords = [SVector(0.0f0, 0.0f0, 0.0f0), SVector(1.1f0, 0.0f0, 0.0f0)]
            # N is species index for N in ANI-2x species map
            species_idx = [pot.species_map["N"], pot.species_map["N"]]

            # Infinite boundary — use CubicBoundary with very large box
            boundary = CubicBoundary(1000.0f0)

            aevs = Molly.compute_aevs(coords, species_idx, nothing, boundary,
                                      pot.aev_params, n_species)

            @test size(aevs) == size(aev_ref)
            @test aevs ≈ aev_ref atol=1e-4
            println("Max AEV deviation: ", maximum(abs.(aevs .- aev_ref)))
        end
    end
end

# ============================================================================
# Test 2: ANIPotential loads from HDF5 with correct structure
# ============================================================================

@testset "ANIPotential: loads from HDF5" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)

        @test length(pot.species_map) == 7
        for elem in ["H", "C", "N", "O", "S", "F", "Cl"]
            @test haskey(pot.species_map, elem)
        end

        # Check AEV params are finite and positive where expected
        @test pot.aev_params.r_c_R > 0
        @test pot.aev_params.r_c_A > 0
        @test pot.cutoff == max(pot.aev_params.r_c_R, pot.aev_params.r_c_A)
        @test !isempty(pot.aev_params.η_R)
        @test !isempty(pot.aev_params.r_s_R)
        @test !isempty(pot.aev_params.η_A)
        @test !isempty(pot.aev_params.r_s_A)
        @test pot.aev_params.ζ > 0
        # AEV length: n_species × n_η_R × n_ShfR + n_pairs × n_η_A × n_ShfZ × n_ShfA
        n_sp   = length(pot.species_map)
        n_pair = n_sp * (n_sp + 1) ÷ 2
        aev_len = n_sp * length(pot.aev_params.η_R) * length(pot.aev_params.r_s_R) +
                  n_pair * length(pot.aev_params.η_A) * length(pot.aev_params.r_s_A) * length(pot.aev_params.θ_s)
        @test aev_len == 1008
        println("ANI-2x: r_c_R=", pot.aev_params.r_c_R, " Å, AEV length = ", aev_len)
    end
end

# ============================================================================
# Test 3: Lux forward pass shape for each element sub-network
# ============================================================================

@testset "ANIPotential: forward pass shape" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)
        n_species  = length(pot.species_map)
        n_pairs    = n_species * (n_species + 1) ÷ 2
        n_rad_per  = length(pot.aev_params.η_R) * length(pot.aev_params.r_s_R)    # EtaR × ShfR
        n_ang_per  = length(pot.aev_params.η_A) * length(pot.aev_params.r_s_A) * length(pot.aev_params.θ_s)
        aev_len    = n_species * n_rad_per + n_pairs * n_ang_per   # should be 1008

        # Use the first ensemble member's parameters for shape check
        ps1 = pot.ps_vec[1]
        st1 = pot.st_vec[1]
        for elem in keys(pot.species_map)
            sym = Symbol(elem)
            model = getfield(pot.model, sym)
            ps    = getfield(ps1, sym)
            st    = getfield(st1, sym)
            x     = randn(Float32, aev_len, 1)   # (aev_length, batch=1)
            y, _  = Lux.apply(model, x, ps, st)
            @test size(y) == (1, 1)
        end
        println("All element sub-networks produce shape (1,1) output ✓")
    end
end

# ============================================================================
# Test 4: Energy sign-check for N₂ dimer (quick sanity, no reference needed)
# ============================================================================

@testset "ANIPotential: N₂ dimer energy sign" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path)

        atoms = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary = CubicBoundary(100.0u"Å")

        sys = System(
            atoms      = atoms,
            coords     = coords,
            boundary   = boundary,
            atoms_data = atoms_data,
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        E = potential_energy(sys)
        @test E < 0u"eV"   # binding energy should be negative
        println("N₂ dimer energy: ", round(typeof(E), E, sigdigits=8))

        # Cross-check against JSON reference if available
        ref_path = joinpath(REF_DIR, "n2_dimer_ani2x.json")
        if isfile(ref_path)
            ref = JSON3.read(read(ref_path, String))
            E_ref = Float64(ref.energy_eV)u"eV"
            @test isapprox(E, E_ref; rtol=1e-3)
            println("TorchANI reference: ", round(typeof(E_ref), E_ref, sigdigits=8))
        end
    end
end

# ============================================================================
# Test 5: Force validation against TorchANI reference for N₂ dimer
# ============================================================================

@testset "ANIPotential: N₂ dimer forces match TorchANI" begin
    ref_path = joinpath(REF_DIR, "n2_dimer_ani2x.json")
    h5_path  = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(ref_path) || !isfile(h5_path)
        @warn "Reference files not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        # forces_eV_per_A is a 2×3 array: [[fx1,fy1,fz1], [fx2,fy2,fz2]]
        f_ref = [SVector{3,Float64}(row...) for row in ref.forces_eV_per_A]

        pot = ANIPotential(h5_path)
        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        sys = System(
            atoms          = atoms,
            coords         = coords,
            boundary       = boundary,
            atoms_data     = atoms_data,
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        fs = forces(sys)
        # Strip units for comparison
        fs_val = [ustrip.(u"eV/Å", f) for f in fs]

        for i in 1:2
            @test isapprox(fs_val[i], f_ref[i]; atol=1e-3)
        end
        # Newton's 3rd law: forces must sum to zero
        @test isapprox(fs_val[1] + fs_val[2], zeros(3); atol=1e-10)

        println("Force on N1: ", round.(fs_val[1], sigdigits=6), " eV/Å")
        println("Force on N2: ", round.(fs_val[2], sigdigits=6), " eV/Å")
        println("Max force deviation: ",
            maximum(abs.(reduce(vcat, fs_val) .- reduce(vcat, f_ref))), " eV/Å")
    end
end

# ============================================================================
# Test 6: Ensemble averaging — all 8 ANI-2x members loaded and averaged
# ============================================================================

@testset "ANIPotential: ensemble averaging" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot_full = ANIPotential(h5_path)                      # all ensemble members
        pot_0    = ANIPotential(h5_path; ensemble_idx=0)      # single member

        @test length(pot_full.ps_vec) == 8
        @test length(pot_full.st_vec) == 8
        @test length(pot_0.ps_vec)    == 1

        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        sys_full = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot_full,), force_units=u"eV/Å", energy_units=u"eV",
        )
        sys_0 = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot_0,), force_units=u"eV/Å", energy_units=u"eV",
        )

        E_full = potential_energy(sys_full)
        E_0    = potential_energy(sys_0)

        @test E_full < 0u"eV"
        # Ensemble mean and single member should agree within ~0.1 eV
        @test isapprox(ustrip(u"eV", E_full), ustrip(u"eV", E_0); atol=0.1)
        println("Ensemble-averaged energy: ", round(typeof(E_full), E_full, sigdigits=8))
        println("Single-member  energy:    ", round(typeof(E_0),    E_0,    sigdigits=8))
    end
end

# ============================================================================
# Test 7: Neighbor-list AEV consistency (O(N²) path vs DistanceNeighborFinder)
# ============================================================================

@testset "ANIPotential: neighbor-list path consistency" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        # Single member for speed; cutoff is the larger of r_c_R and r_c_A
        pot     = ANIPotential(h5_path; ensemble_idx=0)
        n_atoms = 2
        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        # System with DistanceNeighborFinder → uses neighbor-list AEV path
        nf = DistanceNeighborFinder(
            eligible    = trues(n_atoms, n_atoms),
            dist_cutoff = (Float64(pot.cutoff) + 1.0) * u"Å",
        )
        sys_nbr = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
            neighbor_finder=nf,
        )
        # System with no neighbor finder → uses O(N²) AEV path
        sys_full = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
        )

        E_nbr  = potential_energy(sys_nbr)   # neighbor-list path
        E_full = potential_energy(sys_full)  # O(N²) fallback path

        @test isapprox(ustrip(u"eV", E_nbr), ustrip(u"eV", E_full); atol=1e-6)
        println("Energy via neighbor list: ", E_nbr)
        println("Energy via O(N²) path:   ", E_full)
        println("Δ = ", abs(ustrip(u"eV", E_nbr) - ustrip(u"eV", E_full)), " eV")
    end
end

# ============================================================================
# Test 8: End-to-end MD simulation — NVE energy conservation for N₂ dimer
# ============================================================================

@testset "ANIPotential: end-to-end MD simulation (NVE)" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path; ensemble_idx=0)  # single member for speed

        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        sys = System(
            atoms          = atoms,
            coords         = coords,
            boundary       = boundary,
            atoms_data     = atoms_data,
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        # Assign random velocities at 300 K (seeded for reproducibility)
        random_velocities!(sys, 300.0u"K"; rng=MersenneTwister(42))

        E0     = total_energy(sys)
        simulate!(sys, VelocityVerlet(dt=0.1u"fs"), 50)
        E_final = total_energy(sys)

        # NVE: total energy should be approximately conserved
        drift = abs(ustrip(u"eV", E_final - E0)) / abs(ustrip(u"eV", E0))
        @test drift < 0.05   # < 5% relative drift over 50 steps at 0.1 fs
        @test norm(sys.coords[1] - sys.coords[2]) > 0.5u"Å"  # no explosion
        println("Initial total energy: ", round(typeof(E0),      E0,      sigdigits=8))
        println("Final   total energy: ", round(typeof(E_final), E_final, sigdigits=8))
        println("Relative energy drift: ", round(drift * 100, sigdigits=3), " %")
    end
end

# ============================================================================
# Test 9: Enzyme+Zygote two-stage AD forces (only when Enzyme is loaded)
# ============================================================================

if isdefined(@__MODULE__, :Enzyme) || @isdefined(Enzyme)
    @testset "ANIPotential: Enzyme AD forces vs TorchANI (N₂, single-pass)" begin
        ref_path = joinpath(REF_DIR, "n2_dimer_ani2x.json")
        h5_path  = joinpath(REF_DIR, "ani2x.h5")
        if !isfile(ref_path) || !isfile(h5_path)
            @warn "Reference files not found — skipping"
            @test_broken false
        else
            ref = JSON3.read(read(ref_path, String))
            f_ref1 = SVector{3,Float64}(ref.forces_eV_per_A[1]...)

            pot = ANIPotential(h5_path; ensemble_idx=0)
            atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
            coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
            atoms_data = [AtomData(element="N"), AtomData(element="N")]
            boundary   = CubicBoundary(100.0u"Å")

            sys = System(
                atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
                general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
            )

            fs = forces(sys)
            fs_val = [ustrip.(u"eV/Å", f) for f in fs]

            # Tighter tolerance than finite-diff: AD gives exact gradient
            @test isapprox(fs_val[1], f_ref1; atol=1e-4)
            @test isapprox(fs_val[1] + fs_val[2], zeros(3); atol=1e-10)

            println("Enzyme AD force on N1: ", round.(fs_val[1], sigdigits=7), " eV/Å")
            println("Max deviation: ", maximum(abs.(fs_val[1] .- f_ref1)), " eV/Å")
        end
    end
end

# ============================================================================
# Test 10: H₂O AEV validation against TorchANI (multi-element system)
# ============================================================================

@testset "ANIPotential: H₂O AEV matches TorchANI" begin
    ref_path = joinpath(REF_DIR, "water_aevs.json")
    h5_path  = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(ref_path) || !isfile(h5_path)
        @warn "Water AEV reference not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        # ref.aevs is a 3×1008 nested array
        aev_ref = Float32.(reduce(hcat, ref.aevs)')   # (3, 1008)

        pot = ANIPotential(h5_path; ensemble_idx=0)
        n_species = length(pot.species_map)

        # Read coordinates DIRECTLY from the reference JSON to use the exact same
        # Float32 positions TorchANI used when computing the reference AEVs.
        water_ref = JSON3.read(read(joinpath(REF_DIR, "water_ani2x.json"), String))
        coords = [SVector{3, Float32}(row...) for row in water_ref.coordinates_A]
        species_idx = [pot.species_map[s] for s in ["O", "H", "H"]]
        boundary    = CubicBoundary(1000f0)

        aevs = Molly.compute_aevs(coords, species_idx, nothing, boundary,
                                  pot.aev_params, n_species)

        @test size(aevs) == size(aev_ref)
        @test aevs ≈ aev_ref atol=1e-4
        println("H₂O AEV max deviation: ", maximum(abs.(aevs .- aev_ref)))
    end
end

# ============================================================================
# Test 11: H₂O forces match TorchANI (multi-element, non-trivial angular AEV)
# ============================================================================

@testset "ANIPotential: H₂O forces match TorchANI" begin
    ref_path = joinpath(REF_DIR, "water_ani2x.json")
    h5_path  = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(ref_path) || !isfile(h5_path)
        @warn "Water reference not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        f_ref = [SVector{3,Float64}(row...) for row in ref.forces_eV_per_A]

        pot    = ANIPotential(h5_path; ensemble_idx=0)

        atoms = [
            Atom(mass=15.999u"u"),   # O
            Atom(mass=1.008u"u"),    # H1
            Atom(mass=1.008u"u"),    # H2
        ]
        # Use exact coordinates from JSON reference (same Float64 values TorchANI used)
        coords = [SVector{3,Float64}(row...) * u"Å" for row in ref.coordinates_A]
        atoms_data = [AtomData(element="O"), AtomData(element="H"), AtomData(element="H")]
        boundary   = CubicBoundary(100.0u"Å")

        sys = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
        )

        fs     = forces(sys)
        fs_val = [ustrip.(u"eV/Å", f) for f in fs]

        # Float32 AEV + angular terms: ~5 meV/Å precision (TorchANI forces are Float64)
        for i in 1:3
            @test isapprox(fs_val[i], f_ref[i]; atol=5e-3)
        end
        # Newton's 3rd law: forces sum to zero (Float32 precision → ~1e-6 residual)
        @test isapprox(sum(fs_val), zeros(3); atol=1e-6)

        println("H₂O force on O:  ", round.(fs_val[1], sigdigits=6), " eV/Å")
        println("H₂O force on H1: ", round.(fs_val[2], sigdigits=6), " eV/Å")
        println("H₂O force on H2: ", round.(fs_val[3], sigdigits=6), " eV/Å")
        dev = maximum(maximum(abs.(fs_val[i] .- f_ref[i])) for i in 1:3)
        println("Max force deviation: ", round(dev, sigdigits=4), " eV/Å")
    end
end

# ============================================================================
# Test 12: 6mrr protein — energy sign + timing (validates large-system path)
# ============================================================================

@testset "ANIPotential: 6mrr protein energy (first 50 atoms)" begin
    pdb_path = joinpath(@__DIR__, "..", "data", "6mrr_equil.pdb")
    h5_path  = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(pdb_path) || !isfile(h5_path)
        @warn "6mrr_equil.pdb or ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path; ensemble_idx=0)
        valid_elements = Set(keys(pot.species_map))

        # Parse PDB: collect first N atoms whose elements ANI-2x supports
        max_atoms = 50
        coords_list = SVector{3,Float64}[]
        elem_list   = String[]
        open(pdb_path) do f
            for line in eachline(f)
                (startswith(line, "ATOM") || startswith(line, "HETATM")) || continue
                length(line) < 78 && continue
                elem = strip(line[77:78])
                elem in valid_elements || continue
                x = parse(Float64, line[31:38])
                y = parse(Float64, line[39:46])
                z = parse(Float64, line[47:54])
                push!(coords_list, SVector(x, y, z))
                push!(elem_list, elem)
                length(elem_list) == max_atoms && break
            end
        end

        n = length(elem_list)
        atoms      = [Atom(mass=1.0u"u") for _ in 1:n]
        coords     = [c * u"Å" for c in coords_list]
        atoms_data = [AtomData(element=e) for e in elem_list]
        boundary   = CubicBoundary(100.0u"Å")

        nf = DistanceNeighborFinder(
            eligible    = trues(n, n),
            dist_cutoff = (Float64(pot.cutoff) + 1.0) * u"Å",
        )
        sys = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), neighbor_finder=nf,
            force_units=u"eV/Å", energy_units=u"eV",
        )

        # Warmup + energy check
        E = potential_energy(sys)
        @test E < 0u"eV"

        # Timing (second call — buffers warm, neighbor list computed)
        t = @elapsed potential_energy(sys)
        alloc = @allocated potential_energy(sys)
        println("6mrr first $n atoms: E = $(round(typeof(E), E, sigdigits=8))")
        println("  time (warm):  $(round(t*1000, sigdigits=3)) ms")
        println("  allocs (warm): $alloc bytes")
    end
end

# ============================================================================
# Test 13: 6mrr full protein — all 15,954 atoms, cross-validate with TorchANI
# ============================================================================

@testset "ANIPotential: 6mrr full protein energy (all atoms)" begin
    pdb_path = joinpath(@__DIR__, "..", "data", "6mrr_equil.pdb")
    ref_path = joinpath(REF_DIR, "6mrr_ani2x.json")
    h5_path  = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(pdb_path) || !isfile(h5_path)
        @warn "6mrr_equil.pdb or ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path; ensemble_idx=0)
        valid_elements = Set(keys(pot.species_map))

        # Parse all atoms from PDB
        coords_list = SVector{3,Float64}[]
        elem_list   = String[]
        open(pdb_path) do f
            for line in eachline(f)
                (startswith(line, "ATOM") || startswith(line, "HETATM")) || continue
                length(line) < 78 && continue
                elem = strip(line[77:78])
                elem in valid_elements || continue
                x = parse(Float64, line[31:38])
                y = parse(Float64, line[39:46])
                z = parse(Float64, line[47:54])
                push!(coords_list, SVector(x, y, z))
                push!(elem_list, elem)
            end
        end

        n = length(elem_list)
        println("6mrr: loaded $n valid ANI-2x atoms")

        nf = DistanceNeighborFinder(
            eligible    = trues(n, n),
            dist_cutoff = (Float64(pot.cutoff) + 1.0) * u"Å",
        )
        sys = System(
            atoms          = [Atom(mass=1.0u"u") for _ in 1:n],
            coords         = [c * u"Å" for c in coords_list],
            boundary       = CubicBoundary(100.0u"Å"),
            atoms_data     = [AtomData(element=e) for e in elem_list],
            general_inters = (ani=pot,),
            neighbor_finder = nf,
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        E = potential_energy(sys)
        @test E < 0u"eV"

        # Cross-validate against TorchANI if reference is available
        if isfile(ref_path)
            ref = JSON3.read(read(ref_path, String))
            E_ref = Float64(ref.energy_eV) * u"eV"
            # Ensemble member 0 vs ensemble average: allow 1% relative tolerance
            @test isapprox(ustrip(u"eV", E), ustrip(u"eV", E_ref); rtol=0.01)
            println("  Julia E = $(round(typeof(E), E, sigdigits=8))")
            println("  TorchANI E = $(round(typeof(E_ref), E_ref, sigdigits=8))")
        end

        t = @elapsed potential_energy(sys)
        println("  time (warm):  $(round(t, sigdigits=3)) s  ($n atoms)")
    end
end

# ============================================================================
# Test 14: KernelAbstractions AEV kernel — CPU and (optionally) GPU backend
# ============================================================================

if isdefined(@__MODULE__, :KernelAbstractions) || @isdefined(KernelAbstractions)
    @testset "ANIPotential: KA AEV kernel matches scalar CPU (N₂ + H₂O)" begin
        h5_path = joinpath(REF_DIR, "ani2x.h5")
        if !isfile(h5_path)
            @warn "ani2x.h5 not found — skipping"
            @test_broken false
        else
            pot = ANIPotential(h5_path; ensemble_idx=0)
            p   = pot.aev_params
            n_sp = length(pot.species_map)

            # N₂ dimer — only radial AEV (zero angular)
            coords_n2  = [SVector(0f0, 0f0, 0f0), SVector(1.1f0, 0f0, 0f0)]
            species_n2 = [pot.species_map["N"], pot.species_map["N"]]
            bdy        = CubicBoundary(1000f0)

            aevs_cpu = Molly.compute_aevs(coords_n2, species_n2, nothing, bdy, p, n_sp)
            aevs_ka  = Molly.compute_aevs_ka(coords_n2, species_n2, p, n_sp)
            @test aevs_ka ≈ aevs_cpu  atol=1f-6

            # H₂O — non-trivial radial + angular AEV
            water_ref = JSON3.read(read(joinpath(REF_DIR, "water_ani2x.json"), String))
            coords_w  = [SVector{3,Float32}(row...) for row in water_ref.coordinates_A]
            species_w = [pot.species_map[s] for s in ["O","H","H"]]

            aevs_w_cpu = Molly.compute_aevs(coords_w, species_w, nothing, bdy, p, n_sp)
            aevs_w_ka  = Molly.compute_aevs_ka(coords_w, species_w, p, n_sp)
            @test aevs_w_ka ≈ aevs_w_cpu  atol=1f-5

            println("KA N₂ deviation: ", maximum(abs.(aevs_ka .- aevs_cpu)))
            println("KA H₂O deviation: ", maximum(abs.(aevs_w_ka .- aevs_w_cpu)))
        end
    end
end
