# ML potential tests. Reference data is generated by test/torchani_reference.py.
# The packages these tests need (Lux, HDF5, KernelAbstractions, JSON3, ...) are imported by
# runtests.jl; to run this file standalone, first:
#   using Molly, Lux, HDF5, KernelAbstractions, JSON3, LinearAlgebra, Random, Test

# Small reference data (committed); the model weights ani2x.h5 and the large 6mrr_ani2x.json
# come from the lazily-downloaded ANI-2x artifact.
const REF_DIR = joinpath(@__DIR__, "..", "data", "ani_reference")
const ANI_DIR = Molly.ani2x_data_dir()
const ANI_H5  = joinpath(ANI_DIR, "ani2x.h5")

# Parse the 6mrr PDB with BioStructures, keeping only ANI-supported elements (optionally the
# first `limit` of them). Returns (coords in Å as SVector{3,Float64}, element strings).
function load_6mrr_atoms(valid_elements; limit=nothing)
    pdb   = joinpath(@__DIR__, "..", "data", "6mrr_equil.pdb")
    struc = read(pdb, BioStructures.PDBFormat)
    coords_list = SVector{3,Float64}[]
    elem_list   = String[]
    for at in BioStructures.collectatoms(struc)
        el = strip(BioStructures.element(at))
        el in valid_elements || continue
        push!(coords_list, SVector{3,Float64}(BioStructures.coords(at)...))
        push!(elem_list, el)
        limit !== nothing && length(elem_list) == limit && break
    end
    return coords_list, elem_list
end

# ============================================================================
# Test 1: AEV validation against TorchANI for N₂ dimer
# ============================================================================

@testset "ANI AEV: N₂ dimer matches TorchANI reference" begin
    ref_path = joinpath(REF_DIR, "n2_aevs.json")
    if !isfile(ref_path)
        @warn "Reference AEV file not found at $ref_path — run test/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        aev_ref = Float32.(reduce(hcat, ref.aevs)')   # (2, 1008) reference

        # Build the same N₂ dimer system
        # TorchANI ANI-2x default AEV parameters (from torchani source)
        # These must match what torchani_reference.py exports in ani2x.h5
        h5_path = joinpath(ANI_DIR, "ani2x.h5")
        if !isfile(h5_path)
            @warn "ani2x.h5 not found at $h5_path — run test/torchani_reference.py first"
            @test_broken false
        else
            pot = ANIPotential(h5_path)
            n_species = length(pot.species_map)

            # N₂ dimer: 2 N atoms, bond length 1.1 Å, no PBC (infinite box)
            coords = [SVector(0.0f0, 0.0f0, 0.0f0), SVector(1.1f0, 0.0f0, 0.0f0)]
            # N is species index for N in ANI-2x species map
            species_idx = [pot.species_map["N"], pot.species_map["N"]]

            # Infinite boundary — use CubicBoundary with very large box
            boundary = CubicBoundary(1000.0f0)

            aevs = Molly.compute_aevs(coords, species_idx, nothing, boundary,
                                      pot.aev_params, n_species)

            @test size(aevs) == size(aev_ref)
            @test aevs ≈ aev_ref atol=1e-4
        end
    end
end

# ============================================================================
# Test 2: ANIPotential loads from HDF5 with correct structure
# ============================================================================

@testset "ANIPotential: loads from HDF5" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — run test/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)

        @test length(pot.species_map) == 7
        for elem in ["H", "C", "N", "O", "S", "F", "Cl"]
            @test haskey(pot.species_map, elem)
        end

        # Check AEV params are finite and positive where expected
        @test pot.aev_params.r_c_R > 0
        @test pot.aev_params.r_c_A > 0
        @test pot.cutoff == max(pot.aev_params.r_c_R, pot.aev_params.r_c_A)
        @test !isempty(pot.aev_params.η_R)
        @test !isempty(pot.aev_params.r_s_R)
        @test !isempty(pot.aev_params.η_A)
        @test !isempty(pot.aev_params.r_s_A)
        @test pot.aev_params.ζ > 0
        # AEV length: n_species × n_η_R × n_ShfR + n_pairs × n_η_A × n_ShfZ × n_ShfA
        n_sp   = length(pot.species_map)
        n_pair = n_sp * (n_sp + 1) ÷ 2
        aev_len = n_sp * length(pot.aev_params.η_R) * length(pot.aev_params.r_s_R) +
                  n_pair * length(pot.aev_params.η_A) * length(pot.aev_params.r_s_A) * length(pot.aev_params.θ_s)
        @test aev_len == 1008
    end
end

# ============================================================================
# Test 3: Lux forward pass shape for each element sub-network
# ============================================================================

@testset "ANIPotential: forward pass shape" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — run test/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)
        n_species  = length(pot.species_map)
        n_pairs    = n_species * (n_species + 1) ÷ 2
        n_rad_per  = length(pot.aev_params.η_R) * length(pot.aev_params.r_s_R)    # EtaR × ShfR
        n_ang_per  = length(pot.aev_params.η_A) * length(pot.aev_params.r_s_A) * length(pot.aev_params.θ_s)
        aev_len    = n_species * n_rad_per + n_pairs * n_ang_per   # should be 1008

        # Use the first ensemble member's parameters for shape check
        ps1 = pot.ps_vec[1]
        st1 = pot.st_vec[1]
        for elem in keys(pot.species_map)
            sym = Symbol(elem)
            model = getfield(pot.model, sym)
            ps    = getfield(ps1, sym)
            st    = getfield(st1, sym)
            x     = randn(Float32, aev_len, 1)   # (aev_length, batch=1)
            y, _  = Lux.apply(model, x, ps, st)
            @test size(y) == (1, 1)
        end
    end
end

# ============================================================================
# Test 4: N₂ dimer energy matches the TorchANI reference (end-to-end via a System)
# ============================================================================

@testset "ANIPotential: N₂ dimer energy matches TorchANI" begin
    h5_path  = joinpath(ANI_DIR, "ani2x.h5")
    ref_path = joinpath(REF_DIR, "n2_dimer_ani2x.json")
    if !isfile(h5_path) || !isfile(ref_path)
        @warn "ani2x.h5 or n2_dimer_ani2x.json not found — run test/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)
        sys = System(
            atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")],
            coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"],
            boundary   = CubicBoundary(100.0u"Å"),
            atoms_data = [AtomData(element="N"), AtomData(element="N")],
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )
        E     = potential_energy(sys)
        E_ref = Float64(JSON3.read(read(ref_path, String)).energy_eV)u"eV"
        @test E < 0u"eV"                       # binding energy is negative
        @test isapprox(E, E_ref; rtol=1e-3)
    end
end

# ============================================================================
# Test 5: Force validation against TorchANI reference for N₂ dimer
# ============================================================================

@testset "ANIPotential: N₂ dimer forces match TorchANI" begin
    ref_path = joinpath(REF_DIR, "n2_dimer_ani2x.json")
    h5_path  = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(ref_path) || !isfile(h5_path)
        @warn "Reference files not found — run test/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        # forces_eV_per_A is a 2×3 array: [[fx1,fy1,fz1], [fx2,fy2,fz2]]
        f_ref = [SVector{3,Float64}(row...) for row in ref.forces_eV_per_A]

        pot = ANIPotential(h5_path)
        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        sys = System(
            atoms          = atoms,
            coords         = coords,
            boundary       = boundary,
            atoms_data     = atoms_data,
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        fs = forces(sys)
        # Strip units for comparison
        fs_val = [ustrip.(u"eV/Å", f) for f in fs]

        for i in 1:2
            @test isapprox(fs_val[i], f_ref[i]; atol=1e-3)
        end
        # Newton's 3rd law: forces must sum to zero
        @test isapprox(fs_val[1] + fs_val[2], zeros(3); atol=1e-10)

    end
end

# ============================================================================
# Test 5b: unitless coordinates are treated as nm (Molly convention)
# ============================================================================

@testset "ANIPotential: unitless coordinates treated as nm" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path; ensemble_idx=1)
        mksys(coords, bdy, funits, eunits, m) = System(
            atoms=[Atom(mass=m), Atom(mass=m)], coords=coords, boundary=bdy,
            atoms_data=[AtomData(element="N"), AtomData(element="N")],
            general_inters=(ani=pot,), force_units=funits, energy_units=eunits)
        # 1.1 Å bond with units, and the same geometry unitless (0.11 nm == 1.1 Å, read as nm).
        sys_A  = mksys([SVector(0.0,0.0,0.0)u"Å", SVector(1.1,0.0,0.0)u"Å"],
                       CubicBoundary(100.0u"Å"), u"eV/Å", u"eV", 14.0u"u")
        sys_nm = mksys([SVector(0.0,0.0,0.0), SVector(0.11,0.0,0.0)],
                       CubicBoundary(10.0), NoUnits, NoUnits, 14.0)
        # Same physical energy; no-units convention returns kJ/mol, the u"eV" system returns eV.
        E_A_kJ = ustrip(u"kJ * mol^-1", potential_energy(sys_A) * Unitful.Na)
        E_nm   = potential_energy(sys_nm)                                    # kJ/mol
        @test E_nm ≈ E_A_kJ rtol=1e-4
        # Same physical force; no-units convention returns kJ/mol/nm.
        F_A_kJ = [ustrip.(u"kJ * mol^-1 * nm^-1", f * Unitful.Na) for f in Molly.forces(sys_A)]
        F_nm   = Molly.forces(sys_nm)                                        # kJ/mol/nm
        @test F_nm[1] ≈ F_A_kJ[1] rtol=1e-3
    end
end

# ============================================================================
# Test 6: Ensemble averaging — all 8 ANI-2x members loaded and averaged
# ============================================================================

@testset "ANIPotential: ensemble averaging" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot_full = ANIPotential(h5_path)                      # all ensemble members
        pot_0    = ANIPotential(h5_path; ensemble_idx=1)      # single member

        @test length(pot_full.ps_vec) == 8
        @test length(pot_full.st_vec) == 8
        @test length(pot_0.ps_vec)    == 1

        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        sys_full = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot_full,), force_units=u"eV/Å", energy_units=u"eV",
        )
        sys_0 = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot_0,), force_units=u"eV/Å", energy_units=u"eV",
        )

        E_full = potential_energy(sys_full)
        E_0    = potential_energy(sys_0)

        @test E_full < 0u"eV"
        # Ensemble mean and single member should agree within ~0.1 eV
        @test isapprox(ustrip(u"eV", E_full), ustrip(u"eV", E_0); atol=0.1)
    end
end

# ============================================================================
# Test 7: Neighbor-list AEV consistency (O(N²) path vs DistanceNeighborFinder)
# ============================================================================

@testset "ANIPotential: neighbor-list path consistency" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        # Single member for speed; cutoff is the larger of r_c_R and r_c_A
        pot     = ANIPotential(h5_path; ensemble_idx=1)
        n_atoms = 2
        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        # System with DistanceNeighborFinder → uses neighbor-list AEV path
        nf = DistanceNeighborFinder(
            eligible    = trues(n_atoms, n_atoms),
            dist_cutoff = (Float64(pot.cutoff) + 1.0) * u"Å",
        )
        sys_nbr = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
            neighbor_finder=nf,
        )
        # System with no neighbor finder → uses O(N²) AEV path
        sys_full = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
        )

        E_nbr  = potential_energy(sys_nbr)   # neighbor-list path
        E_full = potential_energy(sys_full)  # O(N²) fallback path

        @test isapprox(ustrip(u"eV", E_nbr), ustrip(u"eV", E_full); atol=1e-6)
    end
end

# ============================================================================
# Test 8: End-to-end MD simulation — NVE energy conservation for N₂ dimer
# ============================================================================

@testset "ANIPotential: end-to-end MD simulation (NVE)" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path; ensemble_idx=1)  # single member for speed

        atoms      = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords     = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary   = CubicBoundary(100.0u"Å")

        sys = System(
            atoms          = atoms,
            coords         = coords,
            boundary       = boundary,
            atoms_data     = atoms_data,
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        # Assign random velocities at 300 K (seeded for reproducibility)
        random_velocities!(sys, 300.0u"K"; rng=MersenneTwister(42))

        E0     = total_energy(sys)
        simulate!(sys, VelocityVerlet(dt=0.1f0u"fs"), 50)
        E_final = total_energy(sys)

        # NVE: total energy should be approximately conserved. This is a fast in-suite smoke test.
        drift = abs(ustrip(u"eV", E_final - E0)) / abs(ustrip(u"eV", E0))
        @test drift < 0.05   # < 5% relative drift over 50 steps at 0.1 fs
        @test norm(sys.coords[1] - sys.coords[2]) > 0.5u"Å"  # no explosion
    end
end

# ============================================================================
# Test 10: H₂O AEV validation against TorchANI (multi-element system)
# ============================================================================

@testset "ANIPotential: H₂O AEV matches TorchANI" begin
    ref_path = joinpath(REF_DIR, "water_aevs.json")
    h5_path  = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(ref_path) || !isfile(h5_path)
        @warn "Water AEV reference not found — run test/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        # ref.aevs is a 3×1008 nested array
        aev_ref = Float32.(reduce(hcat, ref.aevs)')   # (3, 1008)

        pot = ANIPotential(h5_path; ensemble_idx=1)
        n_species = length(pot.species_map)

        # Read coordinates DIRECTLY from the reference JSON to use the exact same
        # Float32 positions TorchANI used when computing the reference AEVs.
        water_ref = JSON3.read(read(joinpath(REF_DIR, "water_ani2x.json"), String))
        coords = [SVector{3, Float32}(row...) for row in water_ref.coordinates_A]
        species_idx = [pot.species_map[s] for s in ["O", "H", "H"]]
        boundary    = CubicBoundary(1000f0)

        aevs = Molly.compute_aevs(coords, species_idx, nothing, boundary,
                                  pot.aev_params, n_species)

        @test size(aevs) == size(aev_ref)
        @test aevs ≈ aev_ref atol=1e-4
    end
end

# ============================================================================
# Test 11: H₂O forces match TorchANI (multi-element, non-trivial angular AEV)
# ============================================================================

@testset "ANIPotential: H₂O forces match TorchANI" begin
    ref_path = joinpath(REF_DIR, "water_ani2x.json")
    h5_path  = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(ref_path) || !isfile(h5_path)
        @warn "Water reference not found — run test/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        f_ref = [SVector{3,Float64}(row...) for row in ref.forces_eV_per_A]

        pot    = ANIPotential(h5_path; ensemble_idx=1)

        atoms = [
            Atom(mass=15.999u"u"),   # O
            Atom(mass=1.008u"u"),    # H1
            Atom(mass=1.008u"u"),    # H2
        ]
        # Use exact coordinates from JSON reference (same Float64 values TorchANI used)
        coords = [SVector{3,Float64}(row...) * u"Å" for row in ref.coordinates_A]
        atoms_data = [AtomData(element="O"), AtomData(element="H"), AtomData(element="H")]
        boundary   = CubicBoundary(100.0u"Å")

        sys = System(
            atoms=atoms, coords=coords, boundary=boundary, atoms_data=atoms_data,
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV",
        )

        fs     = forces(sys)
        fs_val = [ustrip.(u"eV/Å", f) for f in fs]

        # Float32 AEV + angular terms: ~5 meV/Å precision (TorchANI forces are Float64)
        for i in 1:3
            @test isapprox(fs_val[i], f_ref[i]; atol=5e-3)
        end
        # Newton's 3rd law: forces sum to zero. FD forces on an asymmetric system
        # (O ≠ H) have no symmetry cancellation, so Float32 FD residual is ~1e-2.
        @test isapprox(sum(fs_val), zeros(3); atol=1e-2)

        dev = maximum(maximum(abs.(fs_val[i] .- f_ref[i])) for i in 1:3)
    end
end

# ============================================================================
# Test 13: 6mrr full protein — all 15,954 atoms, cross-validate with TorchANI
# ============================================================================

@testset "ANIPotential: 6mrr full protein energy (all atoms)" begin
    pot = ANIPotential(ANI_H5; ensemble_idx=1)
    valid_elements = Set(keys(pot.species_map))
    coords_list, elem_list = load_6mrr_atoms(valid_elements)
    n = length(elem_list)

    nf = DistanceNeighborFinder(
        eligible    = trues(n, n),
        dist_cutoff = (Float64(pot.cutoff) + 1.0) * u"Å",
    )
    sys = System(
        atoms           = [Atom(mass=1.0u"u") for _ in 1:n],
        coords          = [c * u"Å" for c in coords_list],
        boundary        = CubicBoundary(100.0u"Å"),
        atoms_data      = [AtomData(element=e) for e in elem_list],
        general_inters  = (ani=pot,),
        neighbor_finder = nf,
        force_units     = u"eV/Å",
        energy_units    = u"eV",
    )

    E = potential_energy(sys)
    @test E < 0u"eV"
    # Cross-validate against TorchANI (single member vs ensemble: 1% tolerance)
    ref = JSON3.read(read(joinpath(ANI_DIR, "6mrr_ani2x.json"), String))
    @test isapprox(ustrip(u"eV", E), Float64(ref.energy_eV); rtol=0.01)
end

# ============================================================================
# Test 14: KernelAbstractions AEV kernel — CPU and (optionally) GPU backend
# ============================================================================

@testset "ANIPotential: KA AEV kernel matches scalar CPU (N₂ + H₂O)" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path; ensemble_idx=1)
        p   = pot.aev_params
        n_sp = length(pot.species_map)

        # N₂ dimer (radial only) and H₂O (radial + angular) scalar-CPU references.
        coords_n2  = [SVector(0f0, 0f0, 0f0), SVector(1.1f0, 0f0, 0f0)]
        species_n2 = [pot.species_map["N"], pot.species_map["N"]]
        bdy        = CubicBoundary(1000f0)
        aevs_n2_cpu = Molly.compute_aevs(coords_n2, species_n2, nothing, bdy, p, n_sp)

        water_ref  = JSON3.read(read(joinpath(REF_DIR, "water_ani2x.json"), String))
        coords_w   = [SVector{3,Float32}(row...) for row in water_ref.coordinates_A]
        species_w  = [pot.species_map[s] for s in ["O","H","H"]]
        aevs_w_cpu = Molly.compute_aevs(coords_w, species_w, nothing, bdy, p, n_sp)

        # The KA kernel must match the scalar CPU path on every backend — CPU and each GPU in
        # array_list. GPU kernels can diverge from the CPU path, so exercise them all.
        for AT in array_list
            aevs_n2 = Array(Molly.compute_aevs_ka(AT(coords_n2), AT(species_n2), p, n_sp))
            @test aevs_n2 ≈ aevs_n2_cpu atol=1f-5
            aevs_w  = Array(Molly.compute_aevs_ka(AT(coords_w), AT(species_w), p, n_sp))
            @test aevs_w  ≈ aevs_w_cpu  atol=1f-5
        end
    end
end

# ============================================================================
# Test 15: threaded AEV matches serial path; batched-by-species NN energy
#          matches the per-atom reference. Run with JULIA_NUM_THREADS>1 to
#          exercise the multithreaded central-atom loop.
# ============================================================================
@testset "ANIPotential: threaded AEV == serial + batched NN energy" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot  = ANIPotential(h5_path; ensemble_idx=1)
        p    = pot.aev_params
        n_sp = length(pot.species_map)
        lux  = Base.get_extension(Molly, :MollyLuxExt)

        # Multi-element slice of 6mrr so both radial and angular AEVs are non-trivial.
        pdb   = joinpath(REF_DIR, "..", "6mrr_equil.pdb")
        valid = Set(keys(pot.species_map))
        coords = SVector{3,Float64}[]; elems = String[]
        if isfile(pdb)
            open(pdb) do f
                for line in eachline(f)
                    (startswith(line, "ATOM") || startswith(line, "HETATM")) || continue
                    length(line) < 78 && continue
                    e = strip(line[77:78]); e in valid || continue
                    push!(coords, SVector(parse(Float64, line[31:38]),
                                          parse(Float64, line[39:46]),
                                          parse(Float64, line[47:54])))
                    push!(elems, e)
                    length(elems) == 300 && break
                end
            end
        end
        if isempty(coords)
            @warn "6mrr_equil.pdb not found — skipping Test 15"
            @test_broken false
        else
            species = [pot.species_map[e] for e in elems]
            n = length(coords); bdy = CubicBoundary(200.0)

            # Serial reference vs the buffered path (threaded when nthreads > 1).
            aevs_serial = Molly.compute_aevs(coords, species, nothing, bdy, p, n_sp)
            buf      = lux.get_aev_buf(pot, n, Val(3), Float64)
            aevs_buf = lux.compute_aevs_buf!(buf, coords, species, nothing, bdy, p, n_sp)
            @test aevs_buf == aevs_serial   # bit-identical: per-atom rows are independent

            # Batched-by-species NN energy matches the per-atom reference.
            sys = System(atoms=[Atom(mass=1.0u"u") for _ in 1:n],
                coords=[c*u"Å" for c in coords], boundary=CubicBoundary(200.0u"Å"),
                atoms_data=[AtomData(element=e) for e in elems],
                general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV")
            E_batched = ustrip(potential_energy(sys))

            idx_to_elem = Dict(v => k for (k, v) in pot.species_map)
            E_ha = 0.0
            for i in 1:n
                s   = species[i]; sym = Symbol(idx_to_elem[s])
                out, _ = Lux.apply(getfield(pot.model, sym),
                                   reshape(Float32.(@view aevs_serial[i, :]), :, 1),
                                   getfield(pot.ps_vec[1], sym), getfield(pot.st_vec[1], sym))
                E_ha += Float64(out[1]) + pot.self_energies[s]
            end
            E_ref = E_ha * Molly.HARTREE_TO_EV
            @test E_batched ≈ E_ref atol=1e-3
        end
    end
end

# ============================================================================
# Test 16: KA neighbour-list AEV kernel matches the all-pairs kernel and the
#          scalar CPU path on a multi-element system. Runs on the KA CPU backend
#          (no GPU needed); the same kernel runs on Metal/CUDA/ROCm.
# ============================================================================
@testset "ANIPotential: KA neighbour-list kernel matches all-pairs (CPU backend)" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    pdb     = joinpath(REF_DIR, "..", "6mrr_equil.pdb")
    if !isfile(h5_path) || !isfile(pdb)
        @warn "ani2x.h5 or 6mrr_equil.pdb not found — skipping"
        @test_broken false
    else
        pot  = ANIPotential(h5_path; ensemble_idx=1)
        p    = pot.aev_params
        n_sp = length(pot.species_map)
        valid = Set(keys(pot.species_map))
        coords = SVector{3,Float64}[]; elems = String[]
        open(pdb) do f
            for line in eachline(f)
                (startswith(line, "ATOM") || startswith(line, "HETATM")) || continue
                length(line) < 78 && continue
                e = strip(line[77:78]); e in valid || continue
                push!(coords, SVector(parse(Float64, line[31:38]),
                                      parse(Float64, line[39:46]),
                                      parse(Float64, line[47:54])))
                push!(elems, e)
                length(elems) == 400 && break
            end
        end
        species = [pot.species_map[e] for e in elems]
        bdy     = CubicBoundary(200.0)
        cpu     = KernelAbstractions.CPU()

        ref      = Molly.compute_aevs(coords, species, nothing, bdy, p, n_sp)
        coords32 = [SVector{3,Float32}(c) for c in coords]   # Metal is Float32-only

        # All-pairs and neighbour-list KA kernels must match the scalar CPU path on every
        # backend — CPU and each GPU in array_list (kernels can diverge on GPU). Float32 coords
        # so the same test runs on Metal; the tolerance absorbs the Float32-vs-Float64 difference.
        for AT in array_list
            cd = AT(coords32); sp = AT(species)
            be = KernelAbstractions.get_backend(cd)
            ka_ap = Array(Molly.compute_aevs_ka(cd, sp, p, n_sp; backend=be))
            ka_nl = Array(Molly.compute_aevs_ka(cd, sp, p, n_sp; backend=be, neighbors=:auto))
            @test ka_ap ≈ ref atol=1e-3
            @test ka_nl ≈ ref atol=1e-3
        end

        # Production path: feed the kernel a real finder NeighborList (what a GPU
        # DistanceNeighborFinder / CPU CellListMapNeighborFinder produce).
        n     = length(coords)
        sys_nl = System(atoms=[Atom(mass=1.0u"u") for _ in 1:n],
            coords=[c*u"Å" for c in coords], boundary=CubicBoundary(200.0u"Å"),
            atoms_data=[AtomData(element=e) for e in elems],
            neighbor_finder=DistanceNeighborFinder(eligible=trues(n,n),
                dist_cutoff=(Float64(pot.cutoff)+1.0)u"Å"),
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV")
        nbrs   = Molly.find_neighbors(sys_nl)
        ka_fnl = Molly.compute_aevs_ka(coords, species, p, n_sp; backend=cpu, neighbors=nbrs)
        @test ka_fnl ≈ ref atol=1e-4

        # Write-reduced kernel (one workgroup per atom, shared-row accumulation).
        ka_wr = Molly.compute_aevs_ka(coords, species, p, n_sp; backend=cpu,
                                      neighbors=nbrs, write_reduce=true, workgroup=16)
        @test ka_wr ≈ ref atol=1e-4

        # The finder NeighborList → device CSR path (nl_to_csr_device) must also run on the GPU
        # backends, where it copies the host pair list onto the device.
        for AT in array_list
            cd = AT(coords32); sp = AT(species)
            be = KernelAbstractions.get_backend(cd)
            ka_dev = Array(Molly.compute_aevs_ka(cd, sp, p, n_sp; backend=be, neighbors=nbrs))
            @test ka_dev ≈ ref atol=1e-3
        end
    end
end

# ============================================================================
# Test 17: end-to-end on-device ANI energy (compute_ani_energy_ka) — GPU AEV +
#          on-device element networks. Runs on the KA CPU backend (no GPU needed);
#          the same path runs on Metal/CUDA. Compared to potential_energy; the small
#          gap is the Float32-AEV (KA) vs Float64-AEV (buffered) precision difference.
# ============================================================================
@testset "ANIPotential: on-device energy (compute_ani_energy_ka, CPU backend)" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    pdb     = joinpath(REF_DIR, "..", "6mrr_equil.pdb")
    if !isfile(h5_path) || !isfile(pdb)
        @warn "ani2x.h5 or 6mrr_equil.pdb not found — skipping"
        @test_broken false
    else
        pot   = ANIPotential(h5_path; ensemble_idx=1)
        n_sp  = length(pot.species_map)
        valid = Set(keys(pot.species_map))
        coords = SVector{3,Float64}[]; elems = String[]
        open(pdb) do f
            for line in eachline(f)
                (startswith(line, "ATOM") || startswith(line, "HETATM")) || continue
                length(line) < 78 && continue
                e = strip(line[77:78]); e in valid || continue
                push!(coords, SVector(parse(Float64, line[31:38]),
                                      parse(Float64, line[39:46]),
                                      parse(Float64, line[47:54])))
                push!(elems, e)
                length(elems) == 100 && break
            end
        end
        species = [pot.species_map[e] for e in elems]
        n = length(coords)
        sys = System(atoms=[Atom(mass=1.0u"u") for _ in 1:n],
            coords=[c*u"Å" for c in coords], boundary=CubicBoundary(200.0u"Å"),
            atoms_data=[AtomData(element=e) for e in elems],
            general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV")
        E_ref = ustrip(potential_energy(sys))                        # CPU, Float64 AEV
        E_ka  = Molly.compute_ani_energy_ka(coords, species, pot, n_sp;
                                            backend=KernelAbstractions.CPU())
        @test isapprox(E_ref, E_ka; atol=0.05)   # ≤ ~5e-4 eV/atom (Float32 AEV gap)
    end
end

# ============================================================================
# Test 18: KA kernels apply the minimum-image convention via Molly.vector, for both
#          CubicBoundary and TriclinicBoundary. Two water molecules are placed near
#          opposite faces of a small periodic box so they are neighbours only through
#          the boundary. The KA kernels (CPU backend) must match the CPU compute_aevs
#          (which already uses vector), and the boundary must change the AEV vs an
#          infinite box. Runs on the KA CPU backend; the same kernels run on Metal/CUDA.
# ============================================================================
@testset "ANIPotential: KA kernels apply minimum-image (Cubic + Triclinic)" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot  = ANIPotential(h5_path; ensemble_idx=1)
        p    = pot.aev_params
        n_sp = length(pot.species_map)
        cpu  = KernelAbstractions.CPU()

        L = 6.0
        coords = SVector{3,Float64}[
            SVector(0.30,3.0,3.0), SVector(0.30,3.0,3.96), SVector(1.20,3.0,3.0),
            SVector(5.70,3.0,3.0), SVector(5.70,3.0,3.96), SVector(4.80,3.0,3.0)]
        species = [pot.species_map[e] for e in ["O","H","H","O","H","H"]]
        n = length(coords)
        cub = CubicBoundary(L)
        tri = TriclinicBoundary(SVector(SVector(L,0.0,0.0), SVector(0.0,L,0.0),
                                        SVector(0.0,0.0,L)))

        for (name, bdy) in (("Cubic", cub), ("Triclinic", tri))
            ref = Molly.compute_aevs(coords, species, nothing, bdy, p, n_sp)
            ka  = Molly.compute_aevs_ka(coords, species, p, n_sp; backend=cpu, boundary=bdy)
            @test ka ≈ ref atol=1e-4
        end

        # The boundary must actually change the AEV vs an infinite (non-periodic) box.
        ka_box = Molly.compute_aevs_ka(coords, species, p, n_sp; backend=cpu, boundary=cub)
        ka_inf = Molly.compute_aevs_ka(coords, species, p, n_sp; backend=cpu)
        @test maximum(abs.(ka_box .- ka_inf)) > 0.1
    end
end

# ============================================================================
# Test 19: on-device ANI forces (the single forces path) — GPU AEV + NN VJP (∂E/∂G) +
#          backward radial/angular kernels (∂E/∂r). Runs on the KA CPU backend (no GPU
#          needed); the same kernels run on Metal/CUDA. Validated three ways on N₂ and H₂O:
#          (1) vs the TorchANI reference (canonical), (2) a finite-difference cross-check on
#          the energy (independent, replaces the former Enzyme cross-check), and (3) that
#          forces(sys) (the AtomsCalculators path) matches the direct call; plus ΣF ≈ 0.
# ============================================================================
@testset "ANIPotential: on-device forces (compute_ani_forces_ka, CPU backend)" begin
    h5_path = joinpath(ANI_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot  = ANIPotential(h5_path)          # full ensemble (matches TorchANI reference)
        n_sp = length(pot.species_map)
        cpu   = KernelAbstractions.CPU()
        bx    = CubicBoundary(100.0u"Å")   # for the System (high-level, unit-carrying)
        bx_ul = CubicBoundary(100.0)       # unitless Å for the direct low-level kernel call
        M = Dict("H"=>1.008, "C"=>12.011, "N"=>14.007, "O"=>15.999,
                 "F"=>18.998, "S"=>32.06, "Cl"=>35.45)

        for jf in ("n2_dimer_ani2x.json", "water_ani2x.json")
            ref   = JSON3.read(read(joinpath(REF_DIR, jf), String))
            elems = String.(ref.species)
            crd   = [SVector{3,Float64}(r...) for r in ref.coordinates_A]
            f_ref = [SVector{3,Float64}(r...) for r in ref.forces_eV_per_A]
            sp    = [pot.species_map[e] for e in elems]

            sys = System(atoms=[Atom(mass=M[e]*u"u") for e in elems],
                coords=[c*u"Å" for c in crd], boundary=bx,
                atoms_data=[AtomData(element=e) for e in elems],
                general_inters=(ani=pot,), force_units=u"eV/Å", energy_units=u"eV")

            f_ka  = Molly.compute_ani_forces_ka(crd, sp, pot, n_sp; backend=cpu, boundary=bx_ul)
            f_sys = [ustrip.(u"eV/Å", f) for f in forces(sys)]   # AtomsCalculators path

            # Independent finite-difference forces from the energy: F = -dE/dr.
            E(c) = ustrip(u"eV", potential_energy(System(sys; coords=[x*u"Å" for x in c])))
            h = 1e-4
            f_fd = map(eachindex(crd)) do a
                SVector{3,Float64}(ntuple(3) do d
                    cp = copy(crd); cm = copy(crd)
                    cp[a] = setindex(cp[a], cp[a][d] + h, d)
                    cm[a] = setindex(cm[a], cm[a][d] - h, d)
                    -(E(cp) - E(cm)) / (2h)
                end)
            end

            @test maximum(maximum(abs.(f_ka[i]  .- f_ref[i])) for i in eachindex(f_ka)) < 3e-3
            @test maximum(maximum(abs.(f_ka[i]  .- f_fd[i]))  for i in eachindex(f_ka)) < 1e-2
            @test maximum(maximum(abs.(f_sys[i] .- f_ka[i]))  for i in eachindex(f_ka)) < 1e-4
            @test isapprox(sum(f_ka), zeros(SVector{3}); atol=1e-6)   # Newton's 3rd law
        end
    end
end

# ============================================================================
# Test 20: GPU path from setup — build the System with GPU coordinates + the ANI interaction,
#          then check that energy, forces and a short simulation match the CPU path. Runs over
#          array_list (each GPU backend on CI); on a CPU-only machine it exercises Array. Uses a
#          unitless Float32 system (nm coordinates, Molly convention) so it also runs on Metal,
#          which is Float32-only and cannot compile broadcasts over unit-carrying arrays.
# ============================================================================
@testset "ANIPotential: GPU path from setup matches CPU" begin
    pot   = ANIPotential(ANI_H5; ensemble_idx=1)
    valid = Set(keys(pot.species_map))
    coords_list, elem_list = load_6mrr_atoms(valid; limit=200)
    n = length(elem_list)
    coords_nm = [SVector{3,Float32}(c ./ 10) for c in coords_list]   # Å → nm (unitless)
    mkatom() = Atom(mass=1.0f0, charge=0.0f0, σ=0.0f0, ϵ=0.0f0, λ=0.0f0)
    mksys(AT) = System(
        atoms          = to_device([mkatom() for _ in 1:n], AT),
        coords         = to_device(copy(coords_nm), AT),
        velocities     = to_device([zero(SVector{3,Float32}) for _ in 1:n], AT),
        boundary       = CubicBoundary(10.0f0),                      # 10 nm
        atoms_data     = [AtomData(element=e) for e in elem_list],
        general_inters = (ani=pot,),
        force_units    = NoUnits,
        energy_units   = NoUnits,
    )
    sys_cpu = mksys(Array)
    E_cpu = potential_energy(sys_cpu)                                # kJ/mol (unitless)
    F_cpu = forces(sys_cpu)                                          # kJ/mol/nm
    maxf  = maximum(norm.(F_cpu))
    for AT in array_list
        sys = mksys(AT)
        @test isapprox(potential_energy(sys), E_cpu; rtol=1e-3)
        F = from_device(forces(sys))
        @test maximum(norm.(F .- F_cpu)) < 1e-2 * maxf
    end
    # Short simulation: CPU and each backend should reach the same coordinates.
    sim_ref = mksys(Array); simulate!(sim_ref, VelocityVerlet(dt=0.0005f0), 10)
    c_ref = from_device(sim_ref.coords)
    for AT in array_list
        sim = mksys(AT); simulate!(sim, VelocityVerlet(dt=0.0005f0), 10)
        @test maximum(norm.(from_device(sim.coords) .- c_ref)) < 1e-3
    end
end
