# ML potential tests
# Run after generating reference data:
#   python scripts/torchani_reference.py --skip-protein
# Then:
#   julia --project -e 'using Molly, Lux, HDF5; include("test/ml_potentials.jl")'

using Molly
using Lux, HDF5
using StaticArrays, Unitful
using Test, JSON3

# Path to reference data generated by scripts/torchani_reference.py
const REF_DIR = joinpath(@__DIR__, "..", "data", "ani_reference")

# ============================================================================
# Test 1: AEV validation against TorchANI for N₂ dimer
# ============================================================================

@testset "ANI AEV: N₂ dimer matches TorchANI reference" begin
    ref_path = joinpath(REF_DIR, "n2_aevs.json")
    if !isfile(ref_path)
        @warn "Reference AEV file not found at $ref_path — run scripts/torchani_reference.py first"
        @test_broken false
    else
        ref = JSON3.read(read(ref_path, String))
        aev_ref = Float32.(reduce(hcat, ref.aevs)')   # (2, 1008) reference

        # Build the same N₂ dimer system
        # TorchANI ANI-2x default AEV parameters (from torchani source)
        # These must match what torchani_reference.py exports in ani2x.h5
        h5_path = joinpath(REF_DIR, "ani2x.h5")
        if !isfile(h5_path)
            @warn "ani2x.h5 not found at $h5_path — run scripts/torchani_reference.py first"
            @test_broken false
        else
            pot = ANIPotential(h5_path)
            n_species = length(pot.species_map)

            # N₂ dimer: 2 N atoms, bond length 1.1 Å, no PBC (infinite box)
            coords = [SVector(0.0f0, 0.0f0, 0.0f0), SVector(1.1f0, 0.0f0, 0.0f0)]
            # N is species index for N in ANI-2x species map
            species_idx = [pot.species_map["N"], pot.species_map["N"]]

            # Infinite boundary — use CubicBoundary with very large box
            boundary = CubicBoundary(1000.0f0)

            aevs = Molly.compute_aevs(coords, species_idx, nothing, boundary,
                                      pot.aev_params, n_species)

            @test size(aevs) == size(aev_ref)
            @test aevs ≈ aev_ref atol=1e-4
            println("Max AEV deviation: ", maximum(abs.(aevs .- aev_ref)))
        end
    end
end

# ============================================================================
# Test 2: ANIPotential loads from HDF5 with correct structure
# ============================================================================

@testset "ANIPotential: loads from HDF5" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)

        @test length(pot.species_map) == 7
        for elem in ["H", "C", "N", "O", "S", "F", "Cl"]
            @test haskey(pot.species_map, elem)
        end

        # Check AEV params are finite and positive where expected
        @test pot.aev_params.r_c_R > 0
        @test pot.aev_params.r_c_A > 0
        @test pot.cutoff == max(pot.aev_params.r_c_R, pot.aev_params.r_c_A)
        @test !isempty(pot.aev_params.η_R)
        @test !isempty(pot.aev_params.r_s_R)
        @test !isempty(pot.aev_params.η_A)
        @test !isempty(pot.aev_params.r_s_A)
        @test pot.aev_params.ζ > 0
        # AEV length: n_species × n_η_R × n_ShfR + n_pairs × n_η_A × n_ShfZ × n_ShfA
        n_sp   = length(pot.species_map)
        n_pair = n_sp * (n_sp + 1) ÷ 2
        aev_len = n_sp * length(pot.aev_params.η_R) * length(pot.aev_params.r_s_R) +
                  n_pair * length(pot.aev_params.η_A) * length(pot.aev_params.r_s_A) * length(pot.aev_params.θ_s)
        @test aev_len == 1008
        println("ANI-2x: r_c_R=", pot.aev_params.r_c_R, " Å, AEV length = ", aev_len)
    end
end

# ============================================================================
# Test 3: Lux forward pass shape for each element sub-network
# ============================================================================

@testset "ANIPotential: forward pass shape" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — run scripts/torchani_reference.py first"
        @test_broken false
    else
        pot = ANIPotential(h5_path)
        n_species  = length(pot.species_map)
        n_pairs    = n_species * (n_species + 1) ÷ 2
        n_rad_per  = length(pot.aev_params.η_R) * length(pot.aev_params.r_s_R)    # EtaR × ShfR
        n_ang_per  = length(pot.aev_params.η_A) * length(pot.aev_params.r_s_A) * length(pot.aev_params.θ_s)
        aev_len    = n_species * n_rad_per + n_pairs * n_ang_per   # should be 1008

        for elem in keys(pot.species_map)
            sym = Symbol(elem)
            model = getfield(pot.model, sym)
            ps    = getfield(pot.ps,    sym)
            st    = getfield(pot.st,    sym)
            x     = randn(Float32, aev_len, 1)   # (aev_length, batch=1)
            y, _  = Lux.apply(model, x, ps, st)
            @test size(y) == (1, 1)
        end
        println("All element sub-networks produce shape (1,1) output ✓")
    end
end

# ============================================================================
# Test 4: Energy sign-check for N₂ dimer (quick sanity, no reference needed)
# ============================================================================

@testset "ANIPotential: N₂ dimer energy sign" begin
    h5_path = joinpath(REF_DIR, "ani2x.h5")
    if !isfile(h5_path)
        @warn "ani2x.h5 not found — skipping"
        @test_broken false
    else
        pot = ANIPotential(h5_path)

        atoms = [Atom(mass=14.0u"u"), Atom(mass=14.0u"u")]
        coords = [SVector(0.0, 0.0, 0.0)u"Å", SVector(1.1, 0.0, 0.0)u"Å"]
        atoms_data = [AtomData(element="N"), AtomData(element="N")]
        boundary = CubicBoundary(100.0u"Å")

        sys = System(
            atoms      = atoms,
            coords     = coords,
            boundary   = boundary,
            atoms_data = atoms_data,
            general_inters = (ani=pot,),
            force_units    = u"eV/Å",
            energy_units   = u"eV",
        )

        E = potential_energy(sys)
        @test E < 0u"eV"   # binding energy should be negative
        println("N₂ dimer energy: ", round(typeof(E), E, sigdigits=8))

        # Cross-check against JSON reference if available
        ref_path = joinpath(REF_DIR, "n2_dimer_ani2x.json")
        if isfile(ref_path)
            ref = JSON3.read(read(ref_path, String))
            E_ref = Float64(ref.energy_eV)u"eV"
            @test isapprox(E, E_ref; rtol=1e-3)
            println("TorchANI reference: ", round(typeof(E_ref), E_ref, sigdigits=8))
        end
    end
end
